##  After learning so much in Numpy, It's time for an assignment. 

### You are a student and today is your Numpy test. The test will consist of 10 questions, purely related to code. You need to write code for the given questions.



#### Q-1 Import Numpy and Write the code to know the version of numpy you are working on ?
Your output should look like this. <br>
NOTE : Numpy version may be different for you.

In [1]:
## write code here
import numpy as np

In [2]:
print(np.__version__)

1.23.5


#### Q - Create a numpy array having elements from 1 to 16 (inclusive) and print it.
Your output should look like this.

In [3]:
## write code here
np.arange(1,17)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

#### Q-3 You need to filter the previous array in such a way that , it only contains odd values.
Note : You have to use boolean indexing.<br>
Your output should look like this.

In [4]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
boolean_mask = array1 % 2 != 0
result = array1[boolean_mask]


In [5]:
print(result)

[1 3 5 7 9]


In [6]:
print(np.arange(1,17,2))

[ 1  3  5  7  9 11 13 15]


In [7]:
array1[array1%2==1]

array([1, 3, 5, 7, 9])

#### Q-4  Replace values that give remainder as 1 when divided by 2 from the above resulted array with 0
Your output should look like this.

In [8]:
## write code here
x=np.arange(1,17)
x[x%2==0]=0

In [9]:
x

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0])

#### Q-5  Change the shape of above resulted array to 4x4.
Your output should look like this.

In [10]:
## write code here
p=x.reshape(4,4)

In [11]:
p

array([[ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0]])

#### Q-6 Stack the resulted array with itself vertically.
Your output should look like this.

In [12]:
## write code here
type((4,5,6))

tuple

In [13]:
array=np.vstack((p,p))

In [14]:
array

array([[ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0],
       [ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0]])

#### Q-7 On this vertical stacked resulted array, reverse the column order in alternate manner. column new order = [ 2,1,4,3 ]
Your output should look like this.

In [15]:
## write code here
array[:,[1,0,3,2]]

array([[ 0,  1,  0,  3],
       [ 0,  5,  0,  7],
       [ 0,  9,  0, 11],
       [ 0, 13,  0, 15],
       [ 0,  1,  0,  3],
       [ 0,  5,  0,  7],
       [ 0,  9,  0, 11],
       [ 0, 13,  0, 15]])

In [16]:
array

array([[ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0],
       [ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0]])

#### Q-8 Calculate , mean , median and mode of the resulting array.
Your output should look like this.

In [17]:
## write code here
p

array([[ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0]])

In [18]:
mean=np.mean(p)
median=np.median(p)

In [19]:
mean

4.0

In [20]:
median

0.5

In [29]:
import statistics

In [30]:
_, idx, count =np.unique(array.reshape(32,),return_index=True,return_counts=True)

In [31]:
index= idx[np.argmax(count)]

In [33]:
array.reshape(32,)[index]

0

In [34]:
array

array([[ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0],
       [ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0]])

In [35]:
mode

0

#### Q-9 Create an array of 5 values , that are selected at random from the above resulted array.
Your output should look like this.

In [36]:
## write code here
array

array([[ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0],
       [ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0]])

In [42]:
random_arr=[np.random.choice(array.reshape(32,))for i in range(5)]

In [43]:
random_arr

[0, 15, 9, 15, 5]

#### Q-10 Complete the function, that calculate the value of this function (a.k.a Binary Cross Entropy) using  Vectorization.
`Given -
    y  : a vector of N dimension,
    y^ : a vector of N dimension
    N : elements in y and y^
    Use : log base 2
    `

<img src="BCE.png" width=500>

Your output should be : 0.011179895048277702

In [55]:
def BCE(y, y_hat):
    ## write code here
    return(y*np.log(y_hat)-(1-y)*np.log(1-y_hat)).mean()

In [56]:
y = np.array([0.13,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.1])
y_hat = np.array([0.2,0.3,0.4,0.3,0.6,0.8,0.7,0.5,0.8,0.1])

result = BCE(y, y_hat)
print(result)

0.007749312731669802


In [57]:
 BCE (y,y_hat)

0.007749312731669802